# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  lint:
    docker:
      - image: 'alpine/helm'
    steps:
      - checkout
      - run:
         name: helm lint
         command: |
           helm lint mycharts
workflows:
  sample:
    jobs:
      - lint
