# Use the latest 2.1 version of CircleCI pipeline process engine
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
#orbs:
  #docker: circleci/docker@2.0.1
  #helm: banzaicloud/helm@0.0.8
  #helm: bizzabo/helm@1.8.0

jobs:
  env_test:
    docker:
      - image: cimg/base:stable
    steps:
      - helm/lint:
          helm-chart-path: mycharts
  banzai:
    docker:
      - image: cimg/base:stable
    steps:
      - helm/lint:
          charts-dir: mycharts
  alpine:
    docker:
      - image: alpine:latest   
    steps:
      - checkout
      - run:
         name: docker
         command: |
           apk add --update docker openrc
           rc-update add docker boot
           docker build -t temp .
               
  lint:
    docker:
      - image: alpine/helm
    steps:
      - checkout
      - run:
         name: helm lint
         command: |
           helm lint mycharts
           helm template temp mycharts
           VERSION=$(git describe --tags | grep -Eo "[0-9].[0-9]-[0-9]+")
           echo $VERSION
           ver=$(echo $VERSION | grep -Eo "[0-9].[0-9]")
           
           git config credential.helper 'cache --timeout=120'
           git config user.email "veeranjaneyule.m@amagi.com"
           git config user.name "veeru-m"

           major=${ver%.*}
           minor=${ver#*.}
           minor=$((minor+1))
           new_tag="$major.$minor"
           echo "new_tag=$new_tag"
           git tag $new_tag
           echo "git tags"
           git tag
           git tag -d $ver
           echo "after deletion"
           git tag
           git push --tags -q https://${GIT_TOKEN}@github.com/veeru-m/circleci-test
           
           echo $(git push origin :$ver -q https://${GIT_TOKEN}@github.com/veeru-m/circleci-test)

           
           helm package --version=$VERSION mycharts
           ls

  template:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
         name: helm
         command: |
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
           helm plugin install https://github.com/sstarcher/helm-release
           helm lint mycharts
           helm template temp mycharts
           VERSION=$(git describe --tags)
           echo $VERSION
           echo "git tab"
           helm package --version=$VERSION mycharts
           ls
workflows:
  sample:
    jobs:
      #- env_test
      - lint:
          context: GITHUB_TOKEN
      #- template
      #- alpine
      #- banzai
