# Use the latest 2.1 version of CircleCI pipeline process engine
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  #docker: circleci/docker@2.0.1
  #helm: banzaicloud/helm@0.0.8

jobs:
  env_test:
    docker:
      - image: cimg/base:stable
    environment:
      MY_VAR: 1
    steps:
      - run:
         name: test
         command: |
           version=$[MY_VAR+1]
           echo $version 
  banzai:
    docker:
      - image: cimg/base:stable
    steps:
      - helm/lint:
          charts-dir: mycharts
  alpine:
    docker:
      - image: alpine:latest   
    steps:
      - checkout
      - run:
         name: docker
         command: |
           apk add --update docker openrc
           rc-update add docker boot
           docker build -t temp .
               
  lint:
    docker:
      - image: alpine/helm
    steps:
      - checkout
      - run:
         name: helm lint
         command: |
           helm lint mycharts
           helm template temp mycharts
  template:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
         name: docker
         command: |
           docker build -t temp .
      - run:
         name: helm
         command: |
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
           helm lint mycharts
           helm template temp mycharts
           wget https://raw.githubusercontent.com/helm/chartmuseum/main/scripts/get-chartmuseum -O chartmuseum.sh
           echo "file permision"
           chmod +x chartmuseum.sh
           echo "executing"
           ./chartmuseum.sh
           echo "finished"
           chartmuseum --version
           chartmuseum --port=8080 --storage="local" --storage-local-rootdir="/temp/charts"
           helm repo add chartmuseum http://localhost:8080
           helm package mycharts
           helm push mycharts/ chartmuseum
           ls
workflows:
  sample:
    jobs:
      #- env_test
      #- lint
      - template
      #- alpine
      #- banzai
