# Use the latest 2.1 version of CircleCI pipeline process engine
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@2.0.1
jobs:
  lint:
    docker:
      - image: alpine/helm
    steps:
      - checkout
      - run:
         name: helm lint
         command: |
           helm lint mycharts
           helm template temp mycharts
  template:
    docker:
      - image: alpine/helm  
    steps:
      - checkout
      - run:
         name: docker
         command: |
           apk add docker
           rc-update add docker boot
           service docker start
           
workflows:
  sample:
    jobs:
      - lint
      - template
