# Use the latest 2.1 version of CircleCI pipeline process engine
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@2.0.1
jobs:
  lint:
    docker:
      - image: alpine/helm
    steps:
      - checkout
      - run:
         name: helm lint
         command: |
           helm lint mycharts
           helm template temp mycharts
  template:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
         name: helm
         command: |
           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
           chmod 700 get_helm.sh
           ./get_helm.sh
workflows:
  sample:
    jobs:
      - lint
      - template
